# ============================================================================
# Basic Config
# 
# ============================================================================

# Baseline year for DOB checks
TestYear = "2017"

# Validations to invoke
# ValidationRoute = ["schema", "local", "id", "dob", "asl"]
# ValidationRoute = ["schema", "id", "dob", "asl", "psi"]
# ValidationRoute = ["schema", "asl", "dob", "id"]

ValidationRoute = ["schema", "schema2", "dob", "id","asl", "psi", "numericvalid"]
# ValidationRoute = ["schema"]

SSFRoute = ["privacy"]
SMSRoute = ["sif2graph"]

# Webserver port
WebServerPort = "1325"

TxReportInterval = 500
UIMessageLimit = 1000
TxStorageLimit = 10000



# ============================================================================
# Advanced parameters
# 
# ============================================================================

# ============================================================================
# Poolsize; number of worker processes to run concurrently
PoolSize = 3
# notes:
# 
# best initial sizing is number of cores on machine -1; each core gets a 
# processor chain, with one left for database processes.
# 
# only run large poolsizes (> 30 workers) on mac/linux, tcp will throttle on
# windows. 
# also note above poolsize 50 on mac increase ulimits from default (256) e.g.
# $ ulimit -n 2048
# otherwise tcp will run out of aviailable file handles
# ============================================================================

# ============================================================================
# Memory Bus model
# "MEM | NATS" | "STAN" are alternatives depending on deployment type
#
# Use "MEM" for standalone low capacity machines and most Windows machines
# which have caps on tcp traffic
#
# Use NATS on capable machines and servers, and is preferred bus for Mac & Linux
# is also used as default bus for clustered installations
#
# Use STAN on same machines as NATS, but when persistent message streams are 
# required - i.e. clients may connect after work has completed
#
# Default build from NSIP is issued with "MEM" selected as majority of standalone
# users are on Windows. If  on Mac/Linux change to NATS for better performance.
#
# STAN streaming server is issued as sperate tool, please contact NSIP if required.
# Remember to set -cluster_id of streaming server to 'nias' if used.

MsgTransport = "NATS"
# MsgTransport = "MEM"
# ============================================================================
